apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: microcks-operator
  namespace: microcks
spec:
  channel: stable
  installPlanApproval: Automatic
  name: microcks
  source: community-operators
  sourceNamespace: openshift-marketplace