apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microcks
  namespace: microcks
spec:
  project: default
  source:
    repoURL: https://github.com/57800-hydroquebec/platform-components.git
    path: microcks-helm
    targetRevision: main
    helm:
      parameters:
        - name: "microcks.url"
          value: "microcks.apps.cluster-gf6zv.gf6zv.sandbox67.opentlc.com"
        - name: "keycloak.url"
          value: "keycloak.apps.cluster-gf6zv.gf6zv.sandbox67.opentlc.com"
  destination:
    server: https://kubernetes.default.svc
    namespace: microcks
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true       
    retry:
      limit: 0 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
