apiVersion: microcks.github.io/v1alpha1
kind: MicrocksInstall
metadata:
  name: {{ .Release.Name }}
spec:
  # Add fields here
  name: {{ .Release.Name }}
  version: {{ .Values.microcks.version }}
  microcks: 
    replicas: {{ .Values.microcks.replicas }}
  postman:
    replicas: {{ .Values.postman.replicas }}
  keycloak:
    install: {{ .Values.keycloak.install }}
    persistent: {{ .Values.keycloak.persistent }}
    volumeSize: {{ .Values.keycloak.volumeSize }}
    replicas: {{ .Values.keycloak.replicas }}
  mongodb:
    install: {{ .Values.mongodb.install }}
    uri: {{ .Values.mongodb.uri }}
    ssl:
      enabled: {{ .Values.mongodb.ssl.enabled }}
      certificateSecret: {{ .Values.mongodb.ssl.certificateSecret }}
    database: {{ .Values.mongodb.database }}
    secretRef:
      secret: {{ .Values.mongodb.secretRef.secret }}
      usernameKey: {{ .Values.mongodb.secretRef.usernameKey }}
      passwordKey: {{ .Values.mongodb.secretRef.passwordKey }}
    persistent: {{ .Values.mongodb.persistent }}
    volumeSize: {{ .Values.mongodb.volumeSize }}
    replicas: {{ .Values.mongodb.replicas }}