apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitbucket
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: "{{ .Values.gitOrg }}/platform-components.git"
    path: bitbucket-helm
    targetRevision: "{{ .Values.gitRef }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: bitbucket
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    retry:
      limit: 0
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
