apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-ci
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/janus-api-idp/platform-components.git
    path: cert-issuer
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    retry:
      limit: 0
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
