kind: Secret
apiVersion: v1
metadata:
  name: {{ include "common.names.fullname" . }}-git-auth
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: backstage
    {{- if .Values.upstream.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.upstream.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  token: "{{ .Values.github.token }}"