apiVersion: v1
kind: Service
metadata:
  {{ template "app.labels" }}
  name: {{ .Values.db.name | default "gitea-db" | quote }}
spec:
  ports:
    - name: postgresql
      nodePort: 0
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: {{ .Values.db.name | default "gitea-db" | quote }}
  sessionAffinity: None
  type: ClusterIP
