apiVersion: apps/v1
kind: Deployment
metadata:
  {{ template "app.labels" }}
  name: {{ .Values.db.name | default "gitea-db" | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.db.name | default "gitea-db" | quote }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.db.name | default "gitea-db" | quote }}
    spec:
      containers:
        - resources:
            limits:
              memory: {{ .Values.db.memory_limit | default "512Mi" }}
          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          name: postgresql
          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - '--live'
            initialDelaySeconds: 120
            timeoutSeconds: 10
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: {{ .Values.db.name | default "gitea-db" | quote }}
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: {{ .Values.db.name | default "gitea-db" | quote }}
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: {{ .Values.db.name | default "gitea-db" | quote }}
          ports:
            - containerPort: 5432
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: {{ .Values.db.name | default "gitea-db" | quote }}
          image: 'registry.redhat.io/rhel8/postgresql-13:latest'
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: {{ .Values.db.name | default "gitea-db" | quote }}
          persistentVolumeClaim:
            claimName: {{ .Values.db.name | default "gitea-db" | quote }}
