apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: {{ default "backstage" .Values.keycloak.backstageClient.name }}
  labels:
    app: backstage
spec:
  realmSelector:
    matchLabels:
      app: backstage
  serviceAccountClientRoles:
    realm-management:
      - query-groups
      - query-users
      - view-users
  client:
    clientId: {{ default "backstage" .Values.keycloak.backstageClient.name }}
    clientAuthenticatorType: client-secret
    secret: {{ .Values.keycloak.backstageClient.secret }}
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    implicitFlowEnabled: false
    defaultClientScopes:
      - profile
      - email
      - roles
    consentRequired: false
    serviceAccountsEnabled: true
    redirectUris:
      - {{ printf "https://backstage-developer-hub.apps.%s/oauth2/callback" .Values.clusterBaseUrl }}