apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: microcks-test
  labels:
    app: microcks-test
spec:
  instanceSelector:
    matchLabels:
      app: keycloak
  realm:
    minimumQuickLoginWaitSeconds: 60
    accessTokenLifespanForImplicitFlow: 900
    enabled: true
    verifyEmail: false
    maxFailureWaitSeconds: 900
    rememberMe: false
    waitIncrementSeconds: 60
    duplicateEmailsAllowed: false
    editUsernameAllowed: false
    realm: microcks-test
    registrationAllowed: false
    permanentLockout: false
    bruteForceProtected: false
    failureFactor: 30
    scopeMappings: []
    id: microcks-test
    accessTokenLifespan: 300
    loginWithEmailAllowed: true
    quickLoginCheckMilliSeconds: 1000
    resetPasswordAllowed: false
    maxDeltaTimeSeconds: 43200
    clients:
      - clientId: microcks-app-js
        enabled: true
        fullScopeAllowed: false
        protocolMappers:
          - config:
              access.token.claim: 'true'
              claim.name: microcks-groups
              full.path: 'true'
              id.token.claim: 'true'
              userinfo.token.claim: 'true'
            consentRequired: false
            name: microcks-group-mapper
            protocol: openid-connect
            protocolMapper: oidc-group-membership-mapper
        publicClient: true
        redirectUris:
          - >-
            https://microcks-microcks.apps.{{ .Values.clusterBaseUrl }}/*
        webOrigins:
          - +
